dbt_project:
  outputs:
    dev:
      host: internal-a369003b390fb40179c49fd47047cd30-1497762862.us-west-1.elb.amazonaws.com
      method: thrift
      port: 10000
      schema: dbt_test
      threads: 1
      type: spark
  target: dev
