acme_retail:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: us-west-2
      s3_data_dir: s3://acme-retail-data/datalake/
      s3_staging_dir: s3://acme-retail-data/dbt/staging/
      schema: acme_retail_silver
      threads: 1
      type: athena
  target: dev
